export const API_Currency_ROOT = "https://min-api.cryptocompare.com/data"

export const CryptoCurrencyTypes = {
  FETCH_LIST_CURRENCY: "FETCH_LIST_CURRENCY",
  FETCH_LIST_CURRENCY_SUCESS: "FETCH_LIST_CURRENCY_SUCESS",
  FETCH_LIST_CURRENCY_PRICE: "FETCH_LIST_CURRENCY_PRICE",
  FETCH_LIST_CURRENCY_PRICE_SUCESS: "FETCH_LIST_CURRENCY_PRICE_SUCESS",
}
